channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=21.2.3
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==1.24.3
  - psutil==7.0.0
  - scikit-learn==1.2.2
  - scipy==1.15.3
name: mlflow-env
